version: '3'
services:
  redux:
    build: ./docker/redux
    environment:
      - NODE_ENV=production
    volumes:
      - ./simple_tuto:/usr/src/app/simple_tuto
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    tty: true # important
    network_mode: "host"
