FROM node:latest
WORKDIR /usr/src/app
RUN npm i -g create-react-native-app
RUN npm i -g expo-cli
#RUN create-react-native-app simple_tuto
#WORKDIR /usr/src/app/simple_tuto
#RUN npm init -y
#RUN npm i react
#RUN npm i redux
#RUN npm i react-redux

